### ISSUE TITLE
Error: compile_raw_db

### ISSUE THREAD

**Issue by ashokpatowary** [kellycochran/IsoPops#8]
I am in trying to compile the file into rawDB; having the following error. Can u look into it?

```
Error in utils::read.table(tsv_filename, stringsAsFactors = F) : 
  no lines available in input
```

**Comment by kellycochran** [comment]
Hello! It is difficult to know what the issue is without a more complete error message, but it looks like either one of your files is empty, or there was an error converting the file to a temporary tsv file. If your files are not in tsv format when they are passed in, the script will try to convert them to tsv format. If the reason for the error is that your file cannot be converted to tsv format, you can try converting the file format yourself and then providing that converted file as input instead. Feel free to email me (kelly.cochran36 at gmail) with more details if you aren't able to work around it!
