### ISSUE TITLE
Error with process_db

### ISSUE THREAD

**Issue by SziKayLeung** [kellycochran/IsoPops#9]
Hello @kellycochran, 

I have successfully created a compile_raw_db but receive an error at the process_db: 

```
> DB_all <- process_db(rawDB, gene_ID_table)
[1] "Processing database..."
Error in names(counts) <- c("ID", "Isoforms") : 
  'names' attribute [2] must be the same length as the vector [1]
In addition: There were 50 or more warnings (use warnings() to see the first 50)]`
```

And the warnings are: 
```
49: In max(transcriptDB$ExonCount[transcriptDB$Gene == x]) :
  no non-missing arguments to max; returning -Inf
50: In max(transcriptDB$ExonCount[transcriptDB$Gene == x]) :
  no non-missing arguments to max; returning -Inf
```

My gene_ID_table is: 
```
> head(gene_ID_table)
   Name      ID
1 Trpa1 PB.18.1
2 Trpa1 PB.18.2
3 Trpa1 PB.18.3
4 Trpa1 PB.18.4
5 Trpa1 PB.18.5
6 Trpa1 PB.18.6
```

I have tried to go back to your Rscript for the compilation, however, was not able to source back to some of the original code for process_db. Any help on this would be greatly appreciated, as I particularly like to try out your filtering code downstream. 

Thank you, 
Szi Kay

**Comment by kellycochran** [comment]
Hi Szi Kay!

The first thing we can fix, to see if that is the problem, is that the gene_ID_table should have 1 line per gene, rather than one line per transcript. In the "ID" column, you should list only the prefix of the PacBio ID that is common to all transcripts for that gene. For example, from the output of `head(gene_ID_table)` you posted, the first line of your gene_ID_table should be `Trpa1  PB.18`. There should be one line for each gene you expect to see transcripts from. Hope this helps!

**Comment by SziKayLeung** [comment]
Hi Kelly, Thank you! It solved the issue right away and I was able to proceed!
